//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Asp_Location_Voitures_2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public System.DateTime Date_reservation { get; set; }
        public System.DateTime Date_retour { get; set; }
        public decimal Montant { get; set; }
        public int LocataireId { get; set; }
        public int VoitureId { get; set; }
    }
}
