//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Asp_Location_Voitures_2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voiture
    {
        public int Id { get; set; }
        public string Marque { get; set; }
        public string Couleur { get; set; }
        public Nullable<int> Annee { get; set; }
        public bool Diponibilite { get; set; }
        public byte[] image_Voiture { get; set; }
        public System.DateTime Location_date { get; set; }
        public int Id_Proprietaire { get; set; }
        public Nullable<int> Id_Locataire { get; set; }
    
        public virtual Locataire Locataire { get; set; }
        public virtual Proprietaire Proprietaire { get; set; }
    }
}
