//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Asp_Location_Voitures_2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voiture
    {
        public int Id { get; set; }
        public string Marque { get; set; }
        public string Couleur { get; set; }
        public Nullable<int> Annee { get; set; }
        public byte[] image_Voiture { get; set; }
        public int Id_Proprietaire { get; set; }
        public decimal Prix { get; set; }
        public Nullable<short> Promotion { get; set; }
    
        public virtual Proprietaire Proprietaire { get; set; }
    }
}
