//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Asp_Location_Voitures_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locataire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locataire()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int Id_Locataire { get; set; }
        public string Email_Loc { get; set; }
        public string Password_Loc { get; set; }
        public string Phone_number_Loc { get; set; }
        public string Adresse_Loc { get; set; }
        public string Name_Loc { get; set; }
        public string Cin_Loc { get; set; }
        public string Permis { get; set; }
        public string Role { get; set; }
        public string image_Loc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
