//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Asp_Location_Voitures_2021.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocationDeVoituresEntities : DbContext
    {
        public LocationDeVoituresEntities()
            : base("name=LocationDeVoituresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Locataire> Locataire { get; set; }
        public virtual DbSet<Proprietaire> Proprietaire { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<Voiture> Voiture { get; set; }
    }
}
