//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Asp_Location_Voitures_2021.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proprietaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proprietaire()
        {
            this.Voiture = new HashSet<Voiture>();
        }

        [Display(Name = "ID :")]
        public int Id_Proprietaire { get; set; }
        [Display(Name = "Nom du propriétaire:")]
        public string Name_Prop { get; set; }
        [Required]
        [Display(Name = "Email :")]
        public string Email_Prop { get; set; }
        [Required(ErrorMessage = "Password is Required.")]
        [Display(Name = "Password :")]
        public string Password_Prop { get; set; }
        [Display(Name = "Phone Number :")]
        public string Phone_number_Prop { get; set; }
        [Display(Name = "Adress :")]
        public string Adresse_Prop { get; set; }
        [Display(Name = "Status :")]
        public string Type { get; set; }
        public string Image_Prop { get; set; }
        public string Role { get; set; }

        public string Image_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voiture> Voiture { get; set; }
    }
}
