//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Asp_Location_Voitures_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamation
    {
        public int Id_Reclamation { get; set; }
        public Nullable<int> Id_Loc { get; set; }
        public Nullable<int> Id_Prop { get; set; }
        public Nullable<System.DateTime> Date_Reclamation { get; set; }
        public string Message { get; set; }
    
        public virtual Locataire Locataire { get; set; }
        public virtual Proprietaire Proprietaire { get; set; }
    }
}
