//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Asp_Location_Voitures_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id_Reservation { get; set; }
        public System.DateTime Date_Reservation { get; set; }
        public decimal Montant { get; set; }
        public int Id_Loc { get; set; }
        public int Id_Voit { get; set; }
        public string Emplacement_Prise { get; set; }
        public string Emplacement_Retour { get; set; }
        public System.DateTime Date_Retour { get; set; }
    
        public virtual Locataire Locataire { get; set; }
        public virtual Voiture Voiture { get; set; }
    }
}
