//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Asp_Location_Voitures_2021.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Voiture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voiture()
        {
            this.Reservation = new HashSet<Reservation>();
        }


        [Display(Name = "ID :")]
        public int Id_Voiture { get; set; }
        [Display(Name = "Marque :")]
        public string Marque { get; set; }
        [Display(Name = "Couleur :")]
        public string Couleur { get; set; }
        [Display(Name = "Année :")]
        public Nullable<int>Annee { get; set; }
        [Display(Name = "ID :")]
        public int Id_Prop { get; set; }
        [Display(Name = "Prix :")]
        public decimal Prix { get; set; }
        [Display(Name = "Promotion :")]
        public Nullable<short>
            Promotion
        { get; set; }
        public string Image_Voiture { get; set; }


        public virtual Proprietaire Proprietaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
